logging:
  level:
    root: INFO
  file:
    name: ./log/bellos-dog-school.log
spring:
  application:
    name: bellos-dog-school
  datasource:
    url: "jdbc:h2:./bellodb;AUTO_SERVER=TRUE;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8080
  error:
    include-message: always